class Block:
    """Minecraft PI block description. Can be sent to Minecraft.setBlock/s"""
    def __init__(self, id, data=0):
        self.id = id
        self.data = data

    def __cmp__(self, rhs):
        return hash(self) - hash(rhs)

    def __hash__(self):
        return (self.id << 8) + self.data

    def withData(self, data):
        return Block(self.id, data)

    def __iter__(self):
        """Allows a Block to be sent whenever id [and data] is needed"""
        return iter((self.id, self.data))
        
    def __repr__(self):
        return "Block(%d, %d)"%(self.id, self.data)

AIR                 = Block(0)
STONE               = Block(1)
GRASS               = Block(2)
DIRT                = Block(3)
COBBLESTONE         = Block(4)
WOOD_PLANKS         = Block(5)
SAPLING             = Block(6)
BEDROCK             = Block(7)
WATER_FLOWING       = Block(8)
WATER               = WATER_FLOWING
WATER_STATIONARY    = Block(9)
LAVA_FLOWING        = Block(10)
LAVA                = LAVA_FLOWING
LAVA_STATIONARY     = Block(11)
SAND                = Block(12)
GRAVEL              = Block(13)
GOLD_ORE            = Block(14)
IRON_ORE            = Block(15)
COAL_ORE            = Block(16)
WOOD                = Block(17)
LEAVES              = Block(18)
GLASS               = Block(20)
LAPIS_LAZULI_ORE    = Block(21)
LAPIS_LAZULI_BLOCK  = Block(22)
SANDSTONE           = Block(24)
BED                 = Block(26)
POWERED_RAIL        = Block(27)
DETECTOR_RAIL       = Block(28)
PSTICKY_PISTON      = Block(29)
COBWEB              = Block(30)
DEAD_SHRUB          = Block(31,0)
GRASS_TALL          = Block(31,1)
FERN                = Block(31,2)
DEAD_BUSH           = Block(32)
PISTON              = Block(33)
PISTON_HEAD         = Block(34)
WOOL                = Block(35,0)
WOOL_WHITE          = Block(35,0)
WOOL_ORANGE         = Block(35,1)
WOOL_MAGENTA        = Block(35,2)
WOOL_LIGHTBLUE      = Block(35,3)
WOOL_YELLOW         = Block(35,4)
WOOL_LIME           = Block(35,5)
WOOL_PINK           = Block(35,6)
WOOL_GRAY           = Block(35,7)
WOOL_LIGHTGRAY      = Block(35,8)
WOOL_CYAN           = Block(35,9)
WOOL_PURPLE         = Block(35,10)
WOOL_BLUE           = Block(35,11)
WOOL_BROWN          = Block(35,12)
WOOL_GREEN          = Block(35,13)
WOOL_RED            = Block(35,14)
WOOL_BLACK          = Block(35,15)
FLOWER_DANDELION    = Block(37)
FLOWER_POPPY        = Block(38,0)
FLOWER_BLUEORCHID   = Block(38,1)
FLOWER_ALLIUM       = Block(38,2)
FLOWER_AZUREBLUET   = Block(38,3)
FLOWER_REDTULIP     = Block(38,4)
FLOWER_ORANGETULIP  = Block(38,5)
FLOWER_WHITETULIP   = Block(38,6)
FLOWER_PINKTULIP    = Block(38,7)
FLOWER_OXEYEDAISY   = Block(38,8)
MUSHROOM_BROWN      = Block(39)
MUSHROOM_RED        = Block(40)
GOLD_BLOCK          = Block(41)
IRON_BLOCK          = Block(42)
STONE_SLAB_DOUBLE   = Block(43)
STONE_SLAB          = Block(44)
BRICK_BLOCK         = Block(45)
TNT                 = Block(46)
BOOKSHELF           = Block(47)
MOSS_STONE          = Block(48)
OBSIDIAN            = Block(49)
TORCH               = Block(50)
FIRE                = Block(51)
STAIRS_WOOD         = Block(53)
CHEST               = Block(54)
DIAMOND_ORE         = Block(56)
DIAMOND_BLOCK       = Block(57)
CRAFTING_TABLE      = Block(58)
FARMLAND            = Block(60)
FURNACE_INACTIVE    = Block(61)
FURNACE_ACTIVE      = Block(62)
DOOR_WOOD           = Block(64)
LADDER              = Block(65)
STAIRS_COBBLESTONE  = Block(67)
DOOR_IRON           = Block(71)
REDSTONE_ORE        = Block(73)
SNOW                = Block(78)
ICE                 = Block(79)
SNOW_BLOCK          = Block(80)
CACTUS              = Block(81)
CLAY                = Block(82)
SUGAR_CANE          = Block(83)
FENCE               = Block(85)
PUMPKIN             = Block(86)
GLOWSTONE_BLOCK     = Block(89)
NETHER_PORTAL       = Block(90)
JACKO_LANTERN       = Block(91)
CAKE_BLOCK          = Block(92)
BEDROCK_INVISIBLE   = Block(95)
STONE_BRICK         = Block(98)
RED_MUSHROOM        = Block(100)
IRON_BARS           = Block(100)
GLASS_PANE          = Block(102)
MELON               = Block(103)
FENCE_GATE          = Block(107)
END_PORTAL          = Block(119)
CARPET_WHITE        = Block(171,0)
CARPET_ORANGE       = Block(171,1)
CARPET_MAGENTA      = Block(171,2)
CARPET_YELLOW       = Block(171,4)
CARPET_LIME         = Block(171,5)
CARPET_PINK         = Block(171,6)
CARPET_GRAY         = Block(171,7)
CARPET_LIGHTGRAY    = Block(171,8)
CARPET_CYAN         = Block(171,9)
CARPET_PURPLE       = Block(171,10)
CARPET_BLUE         = Block(171,11)
CARPET_BROWN        = Block(171,12)
CARPET_GREEN        = Block(171,13)
CARPET_RED          = Block(171,14)
CARPET_BLACK        = Block(171,15)
GLOWING_OBSIDIAN    = Block(246)
NETHER_REACTOR_CORE = Block(247)

